name: Executar Testes JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js e Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'        

      - name: Instalando Dependências do Projeto
        run: yarn install --frozen-lockfile
        working-directory: trabalho-final

      - name: Instalando Browsers do Playwright
        run: npx playwright install
        working-directory: trabalho-final

      - name: Executando Testes E2E
        run: yarn run e2eit
        working-directory: trabalho-final