name: Executar Testes JavaScript

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js e Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Instalando Dependências do Projeto
        run: yarn install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      - name: Garantindo que @playwright/test esteja presente
        run: yarn add @playwright/test@latest --dev
        working-directory: ${{ github.workspace }}

      - name: Instalando Browsers do Playwright
        run: npx playwright install
        working-directory: ${{ github.workspace }}

      - name: Executando Testes E2E
        run: yarn run e2eit
        working-directory: ${{ github.workspace }}